---
name: Test - SHR als Docker Container

"on":
  workflow_dispatch:
    inputs:
      wait:
        description: "Wait 5 minutes at the end of the workflow"
        type: boolean
        required: false
        default: false


permissions:
  contents: read


jobs:
  build:
    runs-on:
      - self-hosted
      - ubuntu-slim

    steps:
      - name: Show runner information
        shell: bash
        run: |
          {
            echo "## Runner information"
            echo ""
            echo "| Property | Value |"
            echo "|---|---|"
            echo "| Name | $RUNNER_NAME |"
            echo "| OS | $RUNNER_OS |"
            echo "| Arch | $RUNNER_ARCH |"
            echo "| Image | $IMAGEDATA_NAME |"
            echo "| Version | $IMAGE_VERSION |"
          }

      - name: List working directory
        shell: bash
        run: ls -lisa

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Print test message
        shell: bash
        run: echo "Hello from self-hosted runner"

      - name: Create test file
        shell: bash
        run: echo "Hallo Welt" > test.txt

      - name: List working directory after file creation
        shell: bash
        run: ls -lisa

      - name: Show current working directory
        shell: bash
        run: pwd

      - name: List /home directory
        shell: bash
        run: ls -lisa /home/

      - name: Show passwd file
        shell: bash
        run: cat /etc/passwd

      - name: Show current user
        shell: bash
        run: whoami

      - name: Show environment variables
        shell: bash
        run: env

      - name: Wait for inspection
        if: ${{ inputs.wait }}
        shell: bash
        run: sleep 300s
